### ISSUE TITLE
Day of the Programmer

### ISSUE THREAD

**Issue by rlaalrud** [mr-sense/hackerrank#3]
link : https://www.hackerrank.com/challenges/day-of-the-programmer/problem?isFullScreen=false

**Comment by mr-sense** [comment]
https://github.com/mr-sense/hackerrank/blob/cefd55dc38625fce7db797625803d53e00066f56/day-of-the-programmer/mk.java#L11-L16
- if else 한줄 코딩 크!!!
- Integer. toString 함수 크!!!

**Comment by mr-sense** [comment]
https://github.com/mr-sense/hackerrank/tree/main/day-of-the-programmer
