### ISSUE TITLE
Forming a Magic Square

### ISSUE THREAD

**Issue by rlaalrud** [mr-sense/hackerrank#5]
link : https://www.hackerrank.com/challenges/magic-square-forming/problem

**Comment by rlaalrud** [comment]
마방진 특성 알아야 풀기 쉬움

**Comment by rlaalrud** [comment]
![스크린샷 2022-05-09 오후 9 54 58](https://user-images.githubusercontent.com/49364743/167414254-7c0a78b0-eb4d-4b26-8a57-23a70819f989.png)

**Comment by mr-sense** [comment]
https://github.com/mr-sense/hackerrank/tree/main/202205W1/magic-square-forming
